rootProject.name = 'JavaClaw'

include 'base'
include 'plugins'
include 'plugins:discord'
include 'plugins:telegram'
include 'plugins:mqtt'
include 'plugins:playwright'
include 'plugins:brave'
include 'providers'
include 'providers:anthropic'
include 'providers:google'
include 'providers:ollama'
include 'providers:openai'
include 'app'
