plugins {
    id 'java-library'
}

dependencies {
    implementation project(':base')
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.5'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
